honeybadger-io/honeybadger-php

examples/config.sample.php
lib/Honeybadger/Exception.php
lib/Honeybadger/Logger.php
tests/Honeybadger/Util/ArrTest.php

This is a small PR to fix some typos - no functional changes

Correct misc typos.

---

lib/Honeybadger/Logger.php

Correct missing passthrough  of parameters in Logger

---

composer.json
lib/Honeybadger/GuzzleFactory.php
lib/Honeybadger/Honeybadger.php
lib/Honeybadger/Sender.php
lib/Honeybadger/TestCase.php
tests/Honeybadger/Backtrace/LineTest.php
tests/Honeybadger/BacktraceTest.php
tests/Honeybadger/HoneybadgerTest.php
tests/Honeybadger/SenderTest.php
tests/Honeybadger/SlimTest.php

See [#42](https://github.com/honeybadger-io/honeybadger-php/pull/42)

Adds test for proxy config

---

lib/Honeybadger/Environment.php
lib/Honeybadger/Util/Arr.php

Resolves #52
* Removes the use of `ARRAY_FILTER_USE_KEY`

Fix PHP 5.5 support

---

src/Contracts/Reporter.php
src/Honeybadger.php
src/HoneybadgerClient.php
tests/HoneyBadgerTest.php

This will allow for additional tooling enhancements.

Return notification response body

---

CHANGELOG.md
src/Honeybadger.php
tests/HoneyBadgerTest.php

**READY**
Adds the ability to reset context.
```php
$honebadger->resetContext();
```
Resolves #63
n/a
```bash
```

Adds the ability to reset context

---

composer.json
tests/ConfigTest.php
tests/EnvironmentTest.php
tests/HoneyBadgerTest.php
tests/LogHandlerTest.php
tests/RequestTest.php
tests/helpers.php

- Updates PHPUnit version
- Resoves `assertArraySubset` warning

Updates to PHPUnit 8

---

CHANGELOG.md
src/Contracts/Reporter.php
src/ExceptionNotification.php
src/Honeybadger.php
src/Request.php
src/Support/Arr.php
tests/ArrTest.php
tests/HoneyBadgerTest.php

Duplicate of #75 with fixed conflicts

Accept grouping options for notification (fixed conflicts)

---

src/LogHandler.php
src/RawNotification.php
tests/HoneyBadgerTest.php
tests/LogHandlerTest.php

Update the log reporter payload to improve error tracking, grouping, and datapoints inside Honeybadger.

Improve log reporter payload

---

src/LogHandler.php
tests/HoneyBadgerTest.php
tests/LogHandlerTest.php

Backporting changes from Version 2.1.0

Backporting changes from Version 2.1.0

---

composer.json

**READY**
Guzzle has been updated to version 7 and causes no issues with HoneyBadger integration

Changed: Allow guzzle 7.0

---

tests/HoneybadgerClientTest.php

Fixes the test from https://github.com/honeybadger-io/honeybadger-php/pull/109

Fix the test associated with the upgrade to Guzzle 7

---

src/Concerns/FiltersData.php
src/Support/Arr.php
tests/ArrTest.php
tests/FiltersDataTest.php

Fixes filtering of non-associative arrays. 
Resolves #116

Fixes filtering of non-associative arrays

---

.github/workflows/run-tests.yml
composer.json
src/Support/Repository.php

Add PHP 8 Support

---

src/BacktraceFactory.php
src/Concerns/FiltersData.php
src/Config.php
src/Support/Arr.php
tests/BacktraceFactoryTest.php
tests/ConfigTest.php
tests/HoneybadgerClientTest.php

Adds the verify key to the config class with a default. Extension of #123

Adds verify for guzzle to the config

---

src/Config.php
src/Exceptions/ServiceExceptionFactory.php
src/Honeybadger.php
src/HoneybadgerClient.php
tests/ConfigTest.php
tests/HoneybadgerClientTest.php
tests/HoneybadgerTest.php
tests/Mocks/Client.php
tests/Mocks/HoneybadgerClient.php

Add endpoint config option (Closes #139)

---

CHANGELOG.md
src/BacktraceFactory.php
src/Honeybadger.php

Fix occasional missing backtrace

---

CHANGELOG.md
src/Checkin.php
src/Honeybadger.php

**READY**
Closes #177. Will open another PR for the laravel package as soon as this one is merged.

feat(check-ins): add support for slug configuration

---

.github/workflows/check-pr-title.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
scripts/SyncSourceCodeWithPackageVersion.php

**READY**
Automates releases with Release Please.

ci: automate releases with release-please

---

src/CheckInsClient.php
src/Config.php
src/Honeybadger.php
tests/ConfigTest.php

feat: make endpoint app url configurable

---

src/Contracts/Reporter.php
src/Honeybadger.php
tests/HoneybadgerTest.php

feat: event context
