honeybadger-io/honeybadger-php

- composer.json
Composer recommends excluding the version and instead it can infer the version from the latest tags.
> Removed version declaration from Composer file

- lib/Honeybadger/Config.php
I haven't tested this, but would be happy to; when I try to run the tests via `phpunit`, I get the following error:
```
PHP Warning:  require_once(/Users/josh/code/honeybadger-php/tests/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/josh/code/honeybadger-php/tests/test_helper.php on line 3
```
It looks like I'm missing a vendor directory -- any ideas? Also, are you aware of how I could test this out in a local composer project before it has been published to packagist? (I'm looking for the equivalent of doing `gem 'honeybadger', path: '../honeybadger-ruby'` in a local Gemfile.)
Sorry for the n00b questions... It has been a while since I worked with PHP. :)
> Read api_key from environment variable.

- README.md
- composer.json
- examples/README.md
These changes alter the composer.json and other areas to align with honeybadger-io. This addresses the intent of #12.
> Alter references to assign maintenance/ownership to Honeybadger-io

- README.md
I made this change thinking it was correct the other day, and after seeing the converted README I researched and determined that unless it is pure JSON (no comments), the javascript formatter looks better.
> Revert change to JSON formatting in Github - just plain ugly.

- .travis.yml
- composer.json
This declares that PHP 7.0 and above is not (yet) supported.
> Warrant and confirm that current PHP API works on PHP 5.3 and higher in 5.x series.

- composer.json
- lib/Honeybadger/Honeybadger.php
- lib/Honeybadger/Logger/Standard.php
- lib/Honeybadger/Sender.php
- tests/Honeybadger/HoneybadgerTest.php
This upgrades Guzzle to v6.2 (current) as well as adding in a default logger that logs to PHP error_log instead of the Logger\Void which would swallow API_KEY errors.
> Guzzle upgrade

- lib/Honeybadger/Config.php
- lib/Honeybadger/Honeybadger.php
- tests/Honeybadger/HoneybadgerTest.php
This reverts 0b7b988dd4834a8c1b3f341e153c1a455bca0a67 and fixes the issue of the configuration instructions blowing up unless you explicitly call `Honeybadger::init()` beforehand. The implication is that FIG compliance is not 100% since there is a side-affect when initializing our library, but we can live with "relaxed compliance" imo.
> Fix bug where $config is not initialized without calling `Honeybadger::init()` first

- README.md
Should we just remove the Laravel 4 instructions?
> Updated instructions for Laravel 5

- lib/Honeybadger/Sender.php
honeybadger-php tries to inject `proxy_user` and `proxy_pass` in proxy URL even when these are not set. The resulting proxy URL is polluted at its beginning with string `:@`, which breaks the call to curl (fails with a timeout).
Note: for reasons unknown, curl does accept string `:@` at the beginning of request URLs, but not at the beginning of proxy URLs.
> Sending through proxy fails when proxy user and proxy pass are not set

- README.md
- lib/Honeybadger/Config.php
- lib/Honeybadger/Environment.php
- tests/Honeybadger/ConfigTest.php
- tests/Honeybadger/EnvironmentTest.php
Resolves #46 
* Adds a new config key, `filter_keys `, to allow for ignore keys from the environment
> Filter environment keys

- CHANGELOG.md
- README.md
- src/Config.php
- src/Honeybadger.php
- tests/ConfigTest.php
- tests/HoneyBadgerTest.php
**READY**
Allow for a `null` config value for `api_key`. Most projects won't set this key for local development environments. When the config key is null, the reporters should do nothing.
n/a
```bash
```
> Allows for null api_key

- CHANGELOG.md
- src/ExceptionNotification.php
- tests/HoneyBadgerTest.php
**READY**
Fixes an issue when merging a custom notifier into the body before sending the request to Honeybadger.
n/a
```bash
```
> Fix custom notifier

- .travis.yml
- CHANGELOG.md
- composer.json
**READY**
Adds PHP 7.3 to the Travis build matrix and removes unnecessary over specification of php versions in the composer manifest. 
n/a
Check CI process of PR
> Add php 73 support

- CHANGELOG.md
- composer.json
- src/Contracts/Reporter.php
- src/Honeybadger.php
- src/HoneybadgerClient.php
- src/LogHandler.php
- src/RawNotification.php
- tests/HoneyBadgerTest.php
- tests/LogHandlerTest.php
**WIP**
Adds a custom Monolog log handler that will send a custom formatted notification to Honeybadger. The custom payload content can be referenced in `tests/LogHandlerTest.php#it_will_format_a_log_for_honeybadger` test.
Resolves #13 
```bash
```
> Add monolog handler

- src/Honeybadger.php
- tests/HoneyBadgerTest.php
**READY**
The existing approach would only prevent reporting if the configured API key was explicitly of type `null`. If the key was an empty string, the API call would be made, and fail.
It is common for API keys to be defined in a `.env` file, and also common for a values to be defined empty, especially in development environments when they are copied from a `.env.example` file and not being used for local development. When a value is left empty, it is parsed as an empty string rather than a null.
None
```bash
```
> Handle empty API key

- src/Config.php
- src/Honeybadger.php
- tests/ConfigTest.php
- tests/HoneyBadgerTest.php
- tests/LogHandlerTest.php
- tests/Mocks/HoneybadgerClient.php
Adds an option for whether the library should send data back to the API, this is useful in testing or staging environments.
```php
new Honeybadger([
'report_data' => false,
])
```
> Add an option to not send data

- CHANGELOG.md
- src/Handlers/ErrorHandler.php
Adds a check to ensure error reporting is enabled for that particular error. Fixes an issue where error suppression does not prevent the error from being reported.
- https://github.com/honeybadger-io/honeybadger-laravel/issues/27
> Update error handler with additional checks

- CHANGELOG.md
- src/BacktraceFactory.php
- tests/BacktraceFactoryTest.php
Adds method arguments to backtrace where available. Resolves #84
The following code creates the following report in HB.
```php
<?php
function foo($foo, $bar)
{
throw new \Exception('Test argument exception');
}
Route::get('/', function () {
foo('asdfasdf', 'th293475239748at');
});
```
```bash
```
> Add method arguments to backtrace

- src/Handlers/ErrorHandler.php
**READY**
Fix exception `call_user_func() expects parameter 1 to be a valid callback, no array or string given` when `set_error_handler()` returns `NULL`.
Just use the lib when user's handler is not set.
> ErrorHandler: call `$this->previousHandler` only if it has callable value

- CHANGELOG.md
- composer.json
- src/BacktraceFactory.php
- tests/BacktraceFactoryTest.php
- tests/HoneyBadgerTest.php
This PR fixes a potential issue with [v1.6.0](https://github.com/honeybadger-io/honeybadger-php/releases/tag/v1.6.0) where invalid JSON gets passed to Honeybadger's API. I can't re-create the issue but I have a theory that there is an issue converting some classes to JSON. The library now only passes the class name if a class is a parameter.
```php
Route::get('/', function (Request $request) {
throwTestError('foo', $request);
return view('welcome');
});
function throwTestError($something, $classThing)
{
throw new \Exception('whoops');
}
```
> Change backtrace arguments to use class name rather than full object

- CHANGELOG.md
- src/ExceptionNotification.php
- src/Honeybadger.php
- src/Support/Repository.php
- tests/HoneyBadgerTest.php
- tests/RepositoryTest.php
By allowing the component and action to be set by the context as well as the additional parameters we can leverage it to easily set the component and action for the Laravel library.
```php
$badger = Honeybadger::new([
'api_key' => 'asdf',
'handlers' => [
'exception' => false,
'error' => false,
],
], $client->make());
$badger->setComponent('HomeController');
$badger->setAction('index');
```
```bash
```
> Allow the component and action to also be set by the library

- src/BacktraceFactory.php
Default backtrace args to an empty array if not defined.
Fixes #90 
```bash
```
1.
> Default args to an empty array

- .travis.yml
- CHANGELOG.md
- composer.json
- src/LogHandler.php
- tests/LogHandlerTest.php
Updates monolog support for monolog@2.0. Fixes issues related to Laravel 6 (https://github.com/honeybadger-io/honeybadger-laravel/issues/38). Removes support for PHP 7.1
```bash
```
> Update monolog support

- CHANGELOG.md
- src/HoneybadgerClient.php
- tests/HoneybadgerClientTest.php
This proposes a fix for https://github.com/honeybadger-io/honeybadger-php/issues/93,
where a recursive payload made the notification to fail because `json_encode`
returns `null` in that case.
**READY** (imho)
As stated in #93 , we have a problem with some exceptions that contain recursive references in their trance. Those cannot be `json_encoded` successfully, so `json_encode` silently returns `null`. Thus this exception won't be reported to the honeybadger backend.
(I don't know 
I provided a test case in `tests/HoneybadgerClientTest.php` that covers that behaviour. Running that test without the fix fails. 
```bash
```
> Use `JSON_PARTIAL_OUTPUT_ON_ERROR` when encoding JSON payload

- CHANGELOG.md
- src/Handlers/ExceptionHandler.php
Added a check to make sure the previous global exception handler is callable before we call it.
> Added a callable check for the exception handler

- .php_cs
- CHANGELOG.md
- src/HoneybadgerClient.php
- tests/HoneybadgerClientTest.php
Backports JSON_PARTIAL_OUTPUT_ON_ERROR fixes to 1.x
> Backports JSON_PARTIAL_OUTPUT_ON_ERROR fixes to 1.x

- src/Honeybadger.php
Updates doc block for `context()` to allow for `array`. I wouldn't recommend sending objects through as it may have unintended side effects.
Resolves #102
> Updates docbloc reference for context to allow array

- src/Handlers/ErrorHandler.php
The order of arguments for mapping the error handler to an
ErrorException were inverted for argument 2 and 3.
Reference https://www.php.net/manual/en/class.errorexception.php
> Fix error handler exception mapping

- src/CustomNotification.php
- src/RawNotification.php
While integrating this into drupal using https://github.com/nathandentzau/drupal-honeybadger and using a custom notification, I noticed that the environment name did not populate in the Honeybadger dashboard.
This PR will add the environment name to custom and raw notifications. It defaults to production because of https://github.com/honeybadger-io/honeybadger-php/blob/master/src/Config.php#L40 .
None
```bash
```
1.
> Add environment to custom and raw notifications

- composer.json
- src/BacktraceFactory.php
- src/Config.php
- src/ExceptionNotification.php
- tests/BacktraceFactoryTest.php
- tests/ConfigTest.php
Adds backtrace frame context for app/vendor.
Reference: https://github.com/honeybadger-io/honeybadger-laravel/issues/9
We'll implement the feature here and then add port the stock configuration to [honeybadger-laravel](https://github.com/honeybadger-io/honeybadger-laravel).
**Notes**
- `vendor_paths` is relative to `project_root`
> Adds backtrace frame context

- src/HoneybadgerClient.php
I was having issues with the guzzle "verify" client option. By default HoneybaderClient sets "verify" to true. Sometimes this is NOT the best option because some developers do NOT have access to the php.ini or openssl configuration. https://docs.guzzlephp.org/en/stable/request-options.html#verify
I commented on #112 (https://github.com/honeybadger-io/honeybadger-php/issues/112#issuecomment-777080461) and @joshuap provided that another issue #121 may be related.
Took a little time and found that in Laravel the client configuration is not brought in generally, instead is specified with specific context as seen in lines 91-92.
I've added the "verify" option that works from Laravel's honeybader configuration. Easy test is to set "verify" to false.
**READY/WIP/HOLD**
A few sentences describing …
> Pass verify option to guzzle config

- src/HoneybadgerClient.php
The latest update breaks laravel installations unless you modify the `config/honeybadger.php` (if you have published it to your config directory), the latest update assumes that the verify option exists in the config, this is not the case if you are upgrading from `honeybadger-laravel 3.4` (or older), so we need a null check here.
> add null check and default value for verify option

- .github/workflows/run-tests.yml
- .gitignore
- src/BacktraceFactory.php
On Windows, file paths use backslashes (`\`) as opposed to Unix forward slashes (`/`). This makes matching of vendor_paths to not work correctly.
> Correctly match vendor_paths on Windows

- composer.json
- phpunit.xml.dist
- src/Config.php
- src/Exceptions/ServiceExceptionFactory.php
- src/HoneybadgerClient.php
- tests/ConfigTest.php
- tests/HoneybadgerClientTest.php
- tests/ServiceExceptionTest.php
**READY**
Allow the user to specify what the library should do when it encounters an error while sending data to Honeybadger. For instance:
```php
$honeybadger = Honeybadger\Honeybadger::new([
'api_key' => 'abc123',
'service_exception_handler' => function (ServiceException $e) {
$logger->warning($e);
},
]);
```
For framework integrations (Laravel and Lumen), the user won't have to worry about this; we'll automatically set the handler to log the exception.
Note: the current default behaviour is to throw, so we need to either change it or prominently mention the behaviour in our docs.
Fixes #121.
Laravel - https://github.com/honeybadger-io/honeybadger-laravel/pull/70
Docs - https://github.com/honeybadger-io/docs/pull/90
> Add support for ServiceException handlers

- src/ArgumentValueNormalizer.php
- src/BacktraceFactory.php
- tests/ArgumentValueNormalizerTest.php
**READY**
This PR introduces an `ArgumentValueNormalizer` class, whose job is to "normalise" arguments before they are serialised and sent to Honeybadger.
The `ArgumentValueNormalizer` will normalize each kind of value properly. For instance:
- For objects, it will replace them with the class name (or whatever we switch to after #133 ).
- For arrays, it will normalize each item up to a maximum number of keys and maximum nesting depth in order to limit the backtrace size. Here's what an array truncated due to excessive nesting looks like:
Currently the defaults are 50 keys per array and a max depth of 10. @stympy let me know if this makes sense.
> Limit backtrace args size (Fixes #122)

- src/ExceptionNotification.php
- tests/HoneyBadgerTest.php
- tests/Mocks/HoneybadgerClient.php
**READY**
See #137 — /PHP's multitasking arrays (they're lists, maps, and everything in between) strike again! Fixed by setting the key to an object rather than array when empty.
> JSON-encode empty arrays properly

- src/ArgumentValueNormalizer.php
- tests/ArgumentValueNormalizerTest.php
- tests/BacktraceFactoryTest.php
**READY**
See https://github.com/honeybadger-io/honeybadger-php/issues/133
This PR renders objects in backtrace arguments as `"[LITERAL]Object(<classname>)"` (example: `"[LITERAL]Object(Illuminate\Http\Request)"`. The `[LITERAL]` token signals to the Honeybadger UI that this should be rendered as-is, without any quotes.
> Render objects as literals (fixes #133)

- src/Contracts/Reporter.php
- src/Honeybadger.php
- tests/HoneyBadgerTest.php
READY
This PR will make it easier to add an array of context values, it also opens up for chaining.
The PR includes tests.
**Before**
```php
foreach ($array as $key => $value) {
$honeybadger->context($key, $value);
}
```
**After**
```php
$honeybadger->withContext($array);
```
And the chaining will allow the exception handler to look something like this (my example is for Laravel).
**Before**
```php
$honeybadger = $this->container->make('honeybadger');
foreach ($array as $key => $value) {
$honeybadger->context($key, $value);
}
$honeybadger->notify($e);
```
**After**
```php
$this->container->make('honeybadger')
->withContext($array)
->notify($e);
```
> add array support to context method and allow chaining

- src/Config.php
- src/Honeybadger.php
- tests/ConfigTest.php
- tests/HoneyBadgerTest.php
This changes `notice['notifier']['name']` to match the format of our
other client libraries (honeybadger-ruby, honeybadger-elixir, etc.).
Also bumps the version for local testing displaying breadcrumbs in
Honeybadger UI.
> Update notifier name

- composer.json
- src/Breadcrumbs.php
- src/Config.php
- src/Contracts/Reporter.php
- src/ExceptionNotification.php
- src/Honeybadger.php
- src/Support/EvictingQueue.php
- tests/BreadcrumbsTest.php
- tests/ConfigTest.php
- tests/HoneybadgerTest.php
**READY**
Implementation of #140
Went with config keys of `breadcrumbs.enabled` and `breadcrumbs.keep`.
Also auto-add breadcrumb for `notice` events, in line with other libraries.
- Docs: (coming soon)
> Add breadcrumbs functionality

- src/Exceptions/ServiceException.php
- src/Exceptions/ServiceExceptionFactory.php
- tests/ServiceExceptionTest.php
**READY**
Currently the `ServiceException::generic()` is thrown in a couple of places where an unknown exception occurred while sending the payload, and it discards the exception that was originally thrown, losing any context. See https://github.com/honeybadger-io/honeybadger-php/blob/95ea3d9702ca83f0784e2ba7db8d66ef087383c4/src/HoneybadgerClient.php#L45-L47. This fixes that.
Additionally, this PR adds an `unexpectedResponseCode()` exception factory, to be used instead of `generic` when the response code is unexpected, since we do know what the problem is.
> Capture the previous exception in generic ServiceException

- src/Config.php
- src/Exceptions/ServiceExceptionFactory.php
- tests/ConfigTest.php
This PR sets a default timeout of 15 seconds for Honeybadger API calls. Since this is PHP, these API calls will most likely be made within the lifetime of the web request. If Honeybagder for some reason is unreachable, without a timeout, this will go on until it hits PHP's max script execution time, crashing their app as a result.
Good read [here](https://medium.com/@masnun/always-use-a-timeout-for-http-requests-de4da538b9e3).
> Set default client timeout

- src/LogHandler.php
- tests/LogHandlerTest.php
- tests/helpers.php
This PR improves the formatting of ERROR logs set via the Monolog log handler, so they look more like exceptions caught via the normal agent. Also unwraps the monolog `context` parameter into Honeybadger context.
This will make it more useful especially in framework integrations like https://github.com/honeybadger-io/honeybadger-laravel/pull/17 — you can use Honeybadger as a logging channel for error logs and still get the same benefits as using it to catch exceptions.
> Monolog handler: Format exceptions properly

- .styleci.yml
- CHANGELOG.md
- src/Concerns/FiltersData.php
- src/Request.php
- tests/RequestTest.php
Fixes #153
I also changed the behaviour of the filter, so it only filters params that have a value. For example, if the request was `?password=mypassword`, you'll get `?password=[FILTERED]`, but if it was `?password=` (no value provided), you'll get it as-is. Might help with debugging problems—the customer can now see that a parameter was not sent.
> Filter query params from request URL

- CHANGELOG.md
- src/BacktraceFactory.php
- src/Config.php
- src/ExceptionNotification.php
- src/Handlers/ErrorHandler.php
- src/Honeybadger.php
- src/Request.php
- tests/ConfigTest.php
PHP separates errors from exceptions, so we need to take that into account. Currently, we wrap errors in ErrorException`, but reporting them that way is misleading, since the stack trace points to where the exception was created.
This PR fixes the stack trace and also changes the reported "class" to report the original error code.
Also added the `capture_deprecations` config flag to turn off reporting of deprecations.
> Special handling of errors

- CHANGELOG.md
- composer.json
- src/BacktraceFactory.php
- src/Honeybadger.php
Closes https://github.com/honeybadger-io/honeybadger-php/issues/164
> Remove uneeded dependency

- .github/workflows/run-tests.yml
- CHANGELOG.md
- src/LogHandler.php
- tests/LogHandlerTest.php
Part of the fix for https://github.com/honeybadger-io/honeybadger-laravel/issues/105
It turns out that setting the minimum log level isn't enough; the handler has to explicitly check that the record passes.
Related:
- https://github.com/honeybadger-io/docs/pull/326
- https://github.com/honeybadger-io/honeybadger-laravel/pull/106
> Log Handler: Ignore non-error logs

- CHANGELOG.md
- src/Checkin.php
- src/CheckinsManager.php
- src/Honeybadger.php
- tests/CheckinsManagerTest.php
> fix(check-ins): do not allow check-ins with same name

- CHANGELOG.md
- src/CheckIn.php
- src/CheckInsClient.php
- src/CheckInsManager.php
- src/Contracts/Reporter.php
- src/Honeybadger.php
- src/HoneybadgerClient.php
- tests/CheckInTest.php
- tests/CheckInsClientTest.php
- tests/CheckInsManagerTest.php
- tests/HoneybadgerTest.php
> feat: make project-id redundant for check-ins configuration api

- CHANGELOG.md
- src/Contracts/Reporter.php
- src/Honeybadger.php
- src/LogEventHandler.php
- tests/HoneybadgerTest.php
- tests/LogEventHandlerTest.php
**READY**
Custom monolog handler to sent monolog records to Events API.
Closes #192.
> feat: events api log instrumentation

- CHANGELOG.md
- src/BulkEventDispatcher.php
- src/Config.php
- src/Contracts/Reporter.php
- src/Handlers/ShutdownHandler.php
- src/Honeybadger.php
- src/HoneybadgerClient.php
- src/LogEventHandler.php
- tests/BulkEventDispatcherTest.php
- tests/ConfigTest.php
- tests/HoneybadgerClientTest.php
- tests/HoneybadgerTest.php
- tests/LogEventHandlerTest.php
**READY**
Honeybadger Insights integration. Adds a `Honeybadger.event()` function that allows sending events to Insights.
Closes: #190
- #192 
- https://github.com/honeybadger-io/docs/issues/503
> feat: events api integration

- CHANGELOG.md
- src/Config.php
- src/Honeybadger.php
- tests/ConfigTest.php
**READY**
- Adds a config check when calling `Honeybadger.flushEvents()`
- Registers shutdown handler by default
> fix: check if events are enabled when calling flushEvents

- src/LogEventHandler.php
- tests/LogEventHandlerTest.php
**READY**
The "Run unit tests" was disabled because it didn't run for 60 days. I have enabled it and it started failing.
This PR:
- reverts to the deprecated usage of logger levels for wider support.
- reverts to reading $record values from array
> fix: revert to deprecated version of logger levels for wider support

- src/Honeybadger.php
- tests/LogEventHandlerTest.php
**READY**
If the API key is not set, there is no point in trying to making the HTTP call.
> fix: check if api key is set in Honeybadger::event

- src/Honeybadger.php
- src/LogEventHandler.php
- tests/BulkEventDispatcherTest.php
- tests/HoneybadgerClientTest.php
- tests/HoneybadgerTest.php
- tests/LogEventHandlerTest.php
Timestamps should be sent with microsecond precision.
> fix: use RFC3339 extended date format

- src/CheckInsClient.php
- src/Contracts/ApiClient.php
- src/HoneybadgerClient.php
**READY**
Sends a `User-Agent` header along with HTTP requests.
The header is made up from the `notifier` config. This way it can be configured to have a different value when being setup from the `honeybadger-laravel` package.
An example value could be:
```
honeybadger-php 2.20.0; 5.3.6-13ubuntu3.2
```
> feat: send user agent in http clients

- src/Exceptions/ServiceException.php
- src/Exceptions/ServiceExceptionFactory.php
- src/HoneybadgerClient.php
- tests/HoneybadgerClientTest.php
> feat: add events api exception message

- src/Honeybadger.php
- tests/HoneybadgerTest.php
**READY**
Skips breadcrumbs that have empty message.
> feat: ignore breadcrumbs with empty message

- .github/workflows/run-tests.yml
- CHANGELOG.md
- src/CheckInsClientWithErrorHandling.php
- src/CheckInsManager.php
- src/Contracts/ApiClient.php
- src/Contracts/Reporter.php
- src/Environment.php
- src/ExceptionNotification.php
- src/Exceptions/ServiceException.php
- src/Handlers/ErrorHandler.php
- src/Honeybadger.php
- src/Request.php
- tests/BacktraceFactoryTest.php
**READY**
This is a fork from https://github.com/the-pulli/honeybadger-php/tree/php-84, which I used to fix the failing tests. The failing tests are because PHP 8.4 introduced better [tracing information for closures](https://tideways.com/profiler/blog/php-8-4-improves-closure-naming-for-simplified-debugging).
Note: I have all debugging information enabled on my local env and I'm getting many deprecated warnings (from guzzle and phpunit). It seems that those have not been addressed yet by the community.
> perf: add PHP 8.4 to test matrix

- src/Exceptions/ServiceException.php
- src/Exceptions/ServiceExceptionFactory.php
**READY**
Fixes #223.
Read error messages from response body instead of relying only on the HTTP status code.
This should handle the cases where a more specific message is included in the response body.
For example, we would show a generic _The API key provided is invalid._ when receiving a 403, but there are cases where the message could be:
- either _You need to upgrade your plan to get cron support._
- or _You have reached your plan's limit for the number of check-ins._
> fix(checkins): read error message from response body

- src/Config.php
- src/Honeybadger.php
- tests/ConfigTest.php
- tests/EventSamplingTest.php
- tests/helpers.php
Give users a configuration option (`events.sample_rate`) to specify what percentage of events will be sent to the API. The configuration option can be overridden with some event metadata (`{_hb: {sample_rate: 100}}`), which allows the user to specify that an event should always be sent, regardless of the default sampling. That metadata will be removed from the event payload before it is sent to the API. 
I tried to stick to the same approach used in the [Ruby implementation](https://github.com/honeybadger-io/honeybadger-ruby/pull/689).
> feat: add Insights event sampling

- src/BulkEventDispatcher.php
- tests/ConfigTest.php
**READY**
I realized that I never increased the defaults as per our discussion [here](https://github.com/honeybadger-io/honeybadger-php/issues/203#issuecomment-2491998036).
I'm actually bumping to 200 and setting the interval seconds to 30.
If the queue has events before these thresholds and the request/job/process is complete, the shutdown handler will kick in (and additionally the terminable middleware in the case of Laravel).
> perf: increase defaults for events dispatcher
